ros-industrial/abb_librws

- CMakeLists.txt
- include/abb_librws/rws_common.h
- package.xml
Instead of manually searching for the components using `find_path(..)` and `find_library(..)`.
e1c8dba also adds a missing header include that I needed to add to get the build to succeed. I'd normally not include that in a PR that changes build infrastructure, but this is really minor and I'd like to avoid opening a lot of 'trivial' PRs.
> Use a CMake find script for Poco libraries

- CMakeLists.txt
For consistency with abb_libegm, see https://github.com/ros-industrial/abb_libegm/commit/2977bf1e50cb24d619dc431190ae6efe47743b8b and the relative discussion https://github.com/ros-industrial/abb_libegm/pull/14 .
> Bump cmake_minimum_required to 2.8.12

- include/abb_librws/rws_interface.h
- include/abb_librws/rws_rapid.h
- src/rws_client.cpp
- src/rws_interface.cpp
- src/rws_rapid.cpp
Reason for the change is that the previous implementation was a bit misleading.
> Renamed methods and updated comments

- include/abb_librws/rws_client.h
- include/abb_librws/rws_poco_client.h
- src/rws_client.cpp
- src/rws_poco_client.cpp
* Minor update to be able to use latest RobotWare
* Added an extra error message field to the communication result
* Renamed the HTTPClientSession instance (for clarity)
Solves issue https://github.com/ros-industrial/abb_librws/issues/22
> Migrated to the latest RobotWare and renamed the HTTPClientSession

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- include/abb_librws/rws_poco_client.h
- src/rws_client.cpp
- src/rws_poco_client.cpp
Updated implementation for setting HTTP and WebSocket communication timeouts.
Solves  https://github.com/ros-industrial/abb_librws/issues/28 and https://github.com/ros-industrial/abb_librws/issues/39
> Updated communication timeouts

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- include/abb_librws/rws_poco_client.h
- src/rws_client.cpp
- src/rws_interface.cpp
- src/rws_poco_client.cpp
This is an attempt to solve #59. It closes the socket in order to interrupt `p_websocket_->receiveFrame()`, and in turn `waitForSubscriptionEvent()`.
A separate mutex is now used for setting `p_websocket_` and for using it. I believe this way there is no unnecessary blocking, but also no unsafe invalidation of `p_websocket_`.
From my understanding, closing the socket before a full frame has been received will make `receiveFrame()` throw a `WebSocketException`, which seems fine to me.
> Add thread-safe way to interrupt waitForSubscriptionEvent().

- include/abb_librws/rws_client.h
- src/rws_client.cpp
Getting a list of all signals is very useful if you're still getting to know the robot. I wanted this functionality for a ROS wrapper we've made at RoboHouse [1]. For now, it needs a forked `abb_librws` with this patch applied.
I was kinda waiting for the other PRs to be merged first, but I suppose I might as well make make this one already.
[1] https://gitlab.com/robohouse/abb_io
> Add RWSClient::getIOSignals().

- include/abb_librws/rws_client.h
- src/rws_client.cpp
This PR removes member variables from `RWSClient` that can also be local variables, as discussed in #59. Among other considerations, this can also help in making `waitForSubscriptionEvent()` and `endSubscription()` thread safe at some point.
Note that this branches off from PR #58 to avoid a future merge conflicts. It probably makes sense to hold off reviewing this until then. The diff should be a lot smaller after #58 is merged.
I also haven't been able to test the library with these changes yet. I think I will be able to do so tommorow.
> Remove RWSClient members that can be local variables.

- src/rws_poco_client.cpp
Fixed error that snuck into the code via PR https://github.com/ros-industrial/abb_librws/pull/58.
I.e. WebSocket creation happened twice, which resulted in an error.
> Removed duplication mistake

- CMakeLists.txt
- include/abb_librws/rws_client.h
- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_common.cpp
- src/rws_interface.cpp
The current implementation of the `getMechanicalUnitRobTarget` function returns the `robtarget` relative to the active `wobj` and `tool` frames. This PR adds the ability to specify those frames as well as the coordinate mode when requesting `robtarget` data.
> Get robtarget relative to specified frames

- include/abb_librws/rws_rapid.h
- src/rws_rapid.cpp
Fix for a bug that was accidently introduced in PR #58.
The bug caused nestled RAPID records to be wrongly parsed.
> Removed reference from input argument

- package.xml
We've been at `1.0.0` for quite some time now, even though changes have accumulated.
I'm not entirely sure whether the migration to plain CMake warrants a major version nr bump, but I'd be open to it.
At the very least we should increase the minor version, so as to be able to distinguish the initial release from the current state.
> Bump version to 1.2.0

- include/abb_librws/rws_rapid.h
- include/abb_librws/rws_state_machine_interface.h
Adds copy constructors to the RAPID record representations, to be able to copy nestled instances.
> Fix nested rapid records copy

- include/abb_librws/rws_common.h
- src/rws_common.cpp
Added a convenience function to check if a `Poco::XML::Node` has a specific attribute.
> Added new function to check for XML node attribute

- include/abb_librws/rws_common.h
- src/rws_common.cpp
> Implemented function to find sub nodes from root node

- include/abb_librws/rws_state_machine_interface.h
- src/rws_state_machine_interface.cpp
As per title.
`EGM` streaming means that `EGM` is used to only send out feedback messages, containing for example. status and current robot position. This is started and stopped via `RAPID` `EGMStreamStart` and `EGMStreamStop` commands in the `RobotWare` `StateMachine Add-In` (if the `EGM` option is present in the robot controller system).
I.e. robot motions are not controlled via `EGM`, meaning that normal `RAPID` motion commands can be used to move the robot (e.g. `MoveAbsJ` and `MoveL`) and still get high frequency feedback via `EGM`.
> Expose start and stop of EGM streaming via the StateMachine Add-In

- include/abb_librws/rws_interface.h
- src/rws_interface.cpp
As per title.
Examples of RAPID symbols in raw text format:
- `num`: `1` or `-2.5`.
- `bool`: `TRUE` or `FALSE`.
- `pos`: `[1, -2, 3.3]`.
- `jointtarget`: `[[1, -2, 3.3, -4.4, 5, 6], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]]`
> Get and set of RAPID symbols in raw text format

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_interface.cpp
As per title.
Enables setting the speed ratio (in the range `[0, 100]`) for RAPID motion commands like `MoveAbsJ` and `MoveL`.
Side note: It would be nicer to use `std::to_string(...)` in [setSpeedRatio(...)](https://github.com/ros-industrial/abb_librws/compare/ros-industrial:e9003df...jontje:5b4a8b7#diff-701777f95fc9b5eff478979c076fa896e78fd32469bac23d21b51772e64b2b5bR821) when/if moving over to `C++11` standard.
> Add methods for getting and setting speed ratio for RAPID motions

- .github/workflows/windows-vcpkg.yml
The Windows `vcpkg` CI started failing two days ago ([see](https://github.com/ros-industrial/abb_librws/actions)).
See https://github.com/ros-industrial/abb_libegm/pull/113#issuecomment-729687257 for the cause.
This PR updates the `vcpkg` and `lukka/run-vcpkg` versions, similar to PR https://github.com/ros-industrial/abb_libegm/pull/114, to fix this.
> Update vcpkg and lukka/run-vcpkg versions

- cmake/abb_librwsConfig.cmake.in
This fixes the install targets that end up in `share/${PROJECT_NAME}/`
Specifically:
```
share/abb_librws/package.xml
share/abb_librws/cmake/*.cmake
```
It also modifies the abb_librwsConfig.cmake, which previously specified the `CMAKE_MODULE_PATH` in relation to `${CMAKE_CURRENT_SOURCE_DIR}`.
This has been tested in a ROS kinetic (ubuntu xenial) environment with abb_librws alongside another package that depended on it. Both of them failed to build with the Poco PPA installed because the `find_package(abb_librws REQUIRED)` would fail from the generated Config.cmake file trying to find Poco.
With the applied fix, it works for both `catkin_make_isolated` and `catkin build`
> Fix "Poco not found" when using an install space

- README.md
---
Edit: updated PR, readme now has 3 lines of badges, similar to `abb_robot_driver`:
> readme: use GHA badges
