- .travis.yml
- setup_poco_ppa.sh
This is for #2.
<del>WIP.</del>
> Add initial Travis config.

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- include/abb_librws/rws_poco_client.h
- include/abb_librws/rws_rapid.h
- include/abb_librws/rws_simple_state_machine_interface.h
- src/rws_interface.cpp
- src/rws_poco_client.cpp
* Added catching of the POCO InvalidArgumentException
* Added another get/set RAPID symbol data method (mainly for convenience)
> Added an exception catch and another get/set RAPID symbol data method

- src/rws_common.cpp
As per title (solves issue #33)
> Fixed memory leakage issue

- README.md
As per title.
Should not be merged until PR https://github.com/ros-industrial/abb_librws/pull/41 has been merged.
> Updated readme with info about RobotWare version

- README.md
As per title.
Clearly shows the license attached to the code.
> readme: add license badge.

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_interface.cpp
As per title.
Solves issue https://github.com/ros-industrial/abb_librws/issues/53.
> Enabled getting only the most recent logged event info

- CONTRIBUTING.md
Recreation of @tfoote's original PR https://github.com/ros-industrial/abb_librws/pull/16.
I have updated it a bit to better fit this repository.
Fixes #52.
> Recreate CONTRIBUTING.md

- setup_poco_ppa.sh
> Update key for ppa:gezakovacs/poco.

- LICENSE
- src/rws_poco_client.cpp
As per title.
No functional changes have been made.
> Fixed whitespaces in all files

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_common.cpp
- src/rws_interface.cpp
Some minor cleanup as per title
> Fix typos and indentation

- .travis.yml
> travis: add Eloquent CI build

- .github/workflows/windows-vcpkg.yml
This is a WIP at this point, as I have no idea what I'm doing.
> Add CI job to test compilation on Windows with vcpkg

- README.md
> readme: use svg support-level badge

- include/abb_librws/rws_common.h
> Updated comments

- .travis.yml
Added latest ROS2 distribution.
> travis: add Foxy CI build

- include/abb_librws/rws_common.h
- src/rws_common.cpp
> Get XML attribute value as a string

- include/abb_librws/rws_client.h
- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect more system info

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect more rapid task info

- include/abb_librws/rws_client.h
- include/abb_librws/rws_interface.h
- src/rws_client.cpp
- src/rws_interface.cpp
> Get mech unit info

- include/abb_librws/rws_cfg.h
- include/abb_librws/rws_interface.h
> Add cfg header

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect arm cfg instances

- include/abb_librws/rws_interface.h
- src/rws_interface.cpp
> Replace get present options

- include/abb_librws/rws_interface.h
- src/rws_interface.cpp
> Collect transmission cfg instances

- include/abb_librws/rws_interface.h
- src/rws_interface.cpp
> Collect joint cfg instances

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect single cfg instances

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect robot cfg instances

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect mech unit cfg instances

- include/abb_librws/rws_common.h
- include/abb_librws/rws_interface.h
- src/rws_common.cpp
- src/rws_interface.cpp
> Collect mech unit group cfg instances

- .github/workflows/windows-vcpkg.yml
See the commit comment for some additional details.
> ci: harmonise 'on' triggers
